name: Test fuzzing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_fuzz:

    runs-on: ubuntu-latest
    container:
      image: mimicria/afler:ub2204
      env:
        AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
        AFL_BENCH_UNTIL_CRASH: 1 
#      ports:
#        - 80
#      volumes:
#        - my_docker_volume:/volume_mount
#      options: --cpus 1
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: AFL_USE_ASAN=1 afl-clang-fast -o test_afl test.c
    - name: Fuzz config
      run: mkdir -p in && mkdir -p out && echo "A" > in/1
#          echo ${{ github.workspace }}
    - name: Fuzz
      run: afl-fuzz -i in -o out -- ./test_afl
    - name: Archive arts
      run: tar -czpf fuzzdir.tgz out/.
    - name: Export arts
      uses: actions/upload-artifact@v4
      with:
        name: fuzzdir
        path: fuzzdir.tgz
