name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: mimicria/afler:ub2204
#      env:
#        NODE_ENV: development
#      ports:
#        - 80
#      volumes:
#        - my_docker_volume:/volume_mount
#      options: --cpus 1
    steps:
    - uses: actions/checkout@v4
    - name: Check for dockerenv file
      run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
    - name: build
      run: AFL_USE_ASAN=1 afl-clang-fast -o test.afl test.c
    - name: fuzz config
      run: mkdir -p in && mkdir -p out && echo "A" > in/1
    - name: fuzz
      run: echo core > /proc/sys/kernel/core_pattern && \
      AFL_BENCH_UNTIL_CRASH=1 afl-fuzz -i in -o out -- ./test_afl
